### ISSUE TITLE
Does llmperf support measuring local disk models? What's the meaning of framework in llmperf.py  line 355?

### ISSUE THREAD

**Issue by zhangjiawei5911** [ray-project/llmperf#11]
I have downloaded llama2-13b-hf to my local disk.
I use this command "python llmperf.py -r 20 -m "../models/Llama-2-13b-chat-hf" to measure the performance of llama2-13b.
But an error occurred.
Traceback (most recent call last):
  File "llmperf.py", line 419, in <module>
    endpoint_config["api_base"] = os.environ["ANYSCALE_API_BASE"]
  File "/opt/conda/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'ANYSCALE_API_BASE'
So， please give me some guidance and advise.

**Comment by zhangjiawei5911** [comment]
It seems like I chose the default framework,but the default framework doesn't match my model.

**Comment by rickyyx** [comment]
You will probably need to setup an Open AI compatible model server to process the requests. 

The script currently only works as a mere client.

**Comment by avnishn** [comment]
going to close this for now as ricky has answered the question.
